config/routes.rb
Rails.application.routes.draw do
    get 'restaurants/index'
    resources :restaurants do
        resources :comments, :foods
    end
    root 'restaurants#index'
    #root :to => "restaurants#show", :id => '1'   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
        has_many :comments
        has_many :foods
        validates :name, presence: true, length: {minimum: 1} 
        validates :image, presence: true, length: {minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @comment = @restaurant.comments.create(comment_params)
        redirect_to restaurant_path(@restaurant)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    
    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @food = @restaurant.foods.new
    end
    
    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @food = @restaurant.foods.create(food_params)
        redirect_to restaurant_path(@restaurant)
    end
    
    def edit
        @restaurant = Restaurant.find(params[:restaurant_id])
        @food = @restaurant.foods.find(params[:id])
    end
    
    def update
        @restaurant = Restaurant.find(params[:restaurant_id])
        @food = @restaurant.foods.find(params[:id])
        if @food.update(food_params)
            redirect_to @restaurant
        else
            render edit_restaurant_food(@food)
        end
    end
    
    def destroy
        @restaurant = Restaurant.find(params[:restaurant_id])
        @food = @restaurant.foods.find(params[:id])
        @food.destroy
        redirect_to restaurant_path(@restaurant)
    end
    
    private
        def food_params
            params.require(:food).permit(:name, :calories, :price)
        end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    
    def index
        @restaurants = Restaurant.all;
    end
    
    def update
        @restaurant = Restaurant.find(params[:id])
        if @restaurant.update(restaurants_params)
            redirect_to restaurants_path
        else
            render 'edit'
        end
    end
    
    def show
        @restaurant = Restaurant.find(params[:id])
        @comments = Comment.all
        @comment = @restaurant.comments.build
        @foods = @restaurant.foods.all
    end
    
    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy
        redirect_to restaurants_path
    end
    
    def edit
        @restaurant = Restaurant.find(params[:id])
    end
    
    def create
        @restaurant = Restaurant.new(restaurants_params)
        if @restaurant.save(restaurants_params)
            redirect_to restaurants_path
        else
            render 'new'
        end
    end
    def new
        @restaurant = Restaurant.new
    end
    
end

private
    def restaurants_params
        params.require(:restaurant).permit(:name, :image)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/foods/edit.html.erb
<h2>Edit the Menu</h2>

<%= form_for([@restaurant, @food]) do |r| %>
    <p>
        <%= r.label 'Name of Food' %><br>
        <%= r.text_field :name %>
    </p>
    
    <p>
        <%= r.label :calories %><br>
        <%= r.text_field :calories %>
    </p>
    
    <p>
        <%= r.label :price %><br>
        <%= r.text_field :price %>
    </p>
    
    <p>
        <%= r.submit "Update" %>
    </p>
    
<% end %>
<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/foods/new.html.erb
<h2>Add to the Menu</h2>
<%= form_for([@restaurant, @food]) do |f| %>
<p>
    <%= f.label 'Name of Food' %><br>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :calories %><br>
    <%= f.text_field :calories %>
</p>
<p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>
<%= link_to 'Back', @restaurant %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media:'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |r| %>
  <div class="topnav">
  <title>App Name Here</title>
  <%= link_to 'Home', controller: 'restaurants' %>
  <a href="/restaurants/1">Bojangles</a>
  <a href="/restaurants/3">Wendy's</a>
  <a href="/restaurants/4">Chick-fil-a</a>
  <a href="/restaurants/5">Feisty's</a>
  <a href="/restaurants/6">Panda Express</a>
  <a href="/restaurants/7">Mondo's Sub</a>
  <a href="/restaurants/8">Papa John's</a>
  <a href="/restaurants/9">Salsarita's</a>
  <a href="/restaurants/10">Sambazon</a>
  <a href="/restaurants/11">Starbucks</a>
  <a href="/restaurants/12">Subway</a>
</div> 
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
        <%= r.label 'Restaurant Name' %><br>
        <%= r.text_field :name %>
    </p>
    <p>
       <%= r.label 'Image Path' %><br>
       <%= r.text_field :image %>
    </p>
    
<p>
    <%= r.submit %>
</p>
    
<% end %>

app/views/restaurants/edit.html.erb
<h>Edit Restaurant</h>
<%= render 'form' %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Fast Food on Campus</h1>
<h2>List of fast food restaurants</h2><br>
<div id="list"><table>
    <th>Restaurant Name</th>
    
    <% @restaurants.each do |restaurant| %>
    <tr>
        <td><%=restaurant.name%></td>
        <td><%=link_to image_tag(restaurant.image), restaurant_path(restaurant)%></td>
        <td><%=link_to 'edit', edit_restaurant_path(restaurant)%></td>
        <td><%=link_to 'delete', restaurant_path(restaurant), method: :delete, data:{confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>

</table></div>
<br><br>
<%= link_to 'Add New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render 'form' %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
  <div class="topnav">
  <title>App Name Here</title>
  <%= link_to 'Home', controller: 'restaurants' %>
  <a href="/restaurants/1">Bojangles</a>
  <a href="/restaurants/3">Wendy's</a>
  <a href="/restaurants/4">Chick-fil-a</a>
  <a href="/restaurants/5">Feisty's</a>
  <a href="/restaurants/6">Panda Express</a>
  <a href="/restaurants/7">Mondo's Sub</a>
  <a href="/restaurants/8">Papa John's</a>
  <a href="/restaurants/9">Salsarita's</a>
  <a href="/restaurants/10">Sambazon</a>
  <a href="/restaurants/11">Starbucks</a>
  <a href="/restaurants/12">Subway</a>
</div> 
<h1><%=@restaurant.name%></h1><br>
<div id="menu">
<h3>&ensp;Menu</h3>
    <% @foods.each do |food| %>
    <p>
        <div id="namespace">&ensp;&ensp;<%= food.name %></div> <div id="caloriesspace"><strong>Calories:</strong> <%= food.calories %></div>
        <div id="pricespace"><strong>Price: $</strong><%= food.price %></div><br>
        <%= link_to 'edit', edit_restaurant_food_path(@restaurant.id, food.id) %> 
    </p><br>
    
    <% end %>

    </div>
<br>
<%= link_to 'Add to the menu', new_restaurant_food_path(@restaurant) %>

<h3>Add a comment: </h3>
<%= form_for([@restaurant, @restaurant.comments.build]) do |r| %>
    <p>
        <%= r.label 'Your Name' %><br>
        <%= r.text_field :commenter %>
    </p>
    
    <p>
        <%= r.label 'Your Comment' %><br>
        <%= r.text_area :body %>
    </p>
    
    <p>
        <%= r.submit %>
    </p>
<% end %>  
<br><br><br>

<h2>Comment Section</h2>
    <% @restaurant.comments.each do |comment| %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>
    
    <div id="line">
    <p>
    <%= comment.body %>
    </p>
    </div>
    
    <% end %>